name: tfsec-pr-commentor
on:
  pull_request:
  workflow_call:
jobs:
  tfsec:
    name: runner / tfsec
    runs-on: ubuntu-latest # Windows and macOS are also supported

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Run tfsec with reviewdog output on the PR
        uses: reviewdog/action-tfsec@master
        with:
          github_token: ${{ secrets.github_token }}
          working_directory: my_directory # Change working directory
          level: info # Get more output from reviewdog
          reporter: github-pr-review # Change reviewdog reporter
          filter_mode: nofilter # Check all files, not just the diff
          fail_on_error: true # Fail action if errors are found
          flags: -tee # Add debug flag to reviewdog
          tfsec_flags: "" # Optional

# name: tfsec-pr-commentor
# on:
#   pull_request:
# jobs:
#   tfsec:
#     name: tfsec PR commenter
#     runs-on: ubuntu-latest

#     steps:
#       - name: Clone repo
#         uses: actions/checkout@master
#       - name: tfsec
#         uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
#         with:
#           # soft_fail_commenter - set to true to to comment silently without breaking the build
#           # tfsec_args: --soft-fail
#           github_token: ${{ github.token }}
